#!/bin/bash

if [[ "$1" == "" ]]; then
    echo "Usage: $0 <path-to-destination-directory>"
    exit 1
fi

sbt assembly

if [ "$?" -gt 0 ]; then
    echo FAILED.
    exit
fi

find . -iname 'smile-core*.jar' | xargs -I{} cp {} $1/smile-core.jar
find . -iname 'smile-math*.jar' | xargs -I{} cp {} $1/smile-math.jar

